image: Visual Studio 2017
platform:
  - x64

clone_folder: c:\gopath\src\github.com\skycoin\skycoin-web

environment:
  GOPATH: c:\gopath

cache:
  - 'electron\node_modules'
  - '%USERPROFILE%\.electron'

install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH\bin;c:\go\bin;%PATH%
  - go version
  - go env
  - ps: Install-Product node 10.15 x64
  - npm install
  - cd electron && npm install && bash ./build-server.sh && cd ..

build_script:
  - make build
  - make build-electron-mac
