image: Visual Studio 2017
platform:
  - x64

clone_folder: c:\gopath\src\github.com\skycoin\skycoin-web

environment:
  GOPATH: c:\gopath

cache:
  - 'electron\node_modules'
  - '%USERPROFILE%\.electron'

install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH\bin;c:\go\bin;%PATH%
  - go version
  - go env
  - ps: Install-Product node 10.15 x64
  - ps: make install-deps-ui

build_script:
  - ps: make build-electron-win

after_build:
  - ps: 7z a skycoin-web.zip c:\gopath\src\github.com\skycoin\skycoin-web\electron\release\*
  - ps: ls *.zip

artifacts:
  - path: skycoin-web.zip
    name: skycoin-web

deploy:
  provider: GitHub
  auth_token: $(GB_AUTH)
  artifact: skycoin-web
  on:
    APPVEYOR_REPO_TAG: true
