dist: xenial
language: node_js
node_js:
  - "10.15"

matrix:
  include:
    - os: linux
      services:
        - docker
    - os: osx
      osx_image: xcode8
# branches:
#   only:
#     - master
#     - develop

env:
  global:
    - ELECTRON_CACHE: $HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE: $HOME/.cache/electron-builder

cache:
  directories:
  - electron/node_modules
  - electron/src/node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder
  - $HOME/.npm/_prebuilds

services:
  - xvfb

addons:
  chrome: stable

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./ci-scripts/add-key.sh; fi

install:
  - npm install
  - cd electron && npm install && ./build-server.sh && cd ..

script:
  # Run 'check' on linux, as osx does not have `docker` service.
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make check; fi || exit 1
  - make lint || exit 1
  - make unit-test || exit 1
  - make build || exit 1
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make build-electron-linux; fi || exit 1
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make build-electron-mac; fi || exit 1

notifications:
  # https://github.com/kvld/travisci-telegram TravisCI Telegram Bot integration
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
