dist: xenial
language: node_js
node_js:
  - "10.15"

matrix:
  include:
    - os: linux
    - os: osx
# branches:
#   only:
#     - master
#     - develop

services:
  - docker

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

install:
  - npm install
  - cd electron && npm install && cd ..

script:
  # Run 'check' on linux, as osx does not have `docker` service.
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make check; fi
  - make lint
  - make unit-test
  - make build
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make build-electron-linux; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make build-electron-mac; fi

notifications:
  # https://github.com/kvld/travisci-telegram TravisCI Telegram Bot integration
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
