dist: xenial
language: node_js
node_js:
  - "10.15"

matrix:
  include:
    - os: linux
      services:
        - docker
    - os: osx
      osx_image: xcode10
# branches:
#   only:
#     - master
#     - develop

services:
  - xvfb

addons:
  chrome: stable
  # apt:
  #   sources:
  #     - google-chrome
  #   packages:
  #     - google-chrome-stable

install:
  - npm install
  - cd electron && npm install && cd ..

script:
  # Run 'check' on linux, as osx does not have `docker` service.
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make check; fi || exit 1
  - make lint || exit 1
  - make unit-test || exit 1
  - make build || exit 1
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make build-electron-linux; fi || exit 1
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make build-electron-mac; fi || exit 1

notifications:
  # https://github.com/kvld/travisci-telegram TravisCI Telegram Bot integration
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
