dist: xenial
language: node_js
node_js:
  - "6.9"

matrix:
  include:
    - os: linux
    - os: osx
# branches:
#   only:
#     - master
#     - develop

services:
  - docker

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_script:
  - npm install
  - cd electron && npm install

script:
  - make check
  - make build

notifications:
  # https://github.com/kvld/travisci-telegram TravisCI Telegram Bot integration
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
